### 错误处理
* 在请求错误时进行的处理
```
    axios.get("/data.json").then(res=>{
        console.log(res)
    }).catch(err => {
        console.log(err)
    })
```
* 请求成功后，会进入到.then()中
* 请求出错后，会进入到.catch() 中

* 请求错误常见的有： 404---找不到   401--超时
* **无论是请求错误还是响应错误，最终都会进入.catch()里面**

### 例子： 实际开发过程中，一般都需要添加统一的错误处理
* 包括请求错误和响应错误
* 实际开发中，都是给实例统一添加拦截器，统一处理错误
* 不会给每个接口单独添加错误处理，因为这样不便于维护

```
    let instance = axios.create({})
    instance.interceptors.request.use(config => {
        return config
    }, err => {
        // 请求错误 一般http状态码以 4 开头
        // 常见401超时 404 not found
        $("#modal").show();
        setTimeout(()=>{
            $("#modal").hide();
        },2000)
        return Promise.reject(err)
    })

    instance.interceptors.response.use(res=>{
        return res
    }, err => {
        // 响应错误处理  一般http状态码以5开头 
        // 500--系统错误 502---系统重启
        $("#modal").show();
        setTimeout(()=>{
            $("#modal").hide();
        },2000)
        return Promise.reject(err)
    })

    // 这样在请求接口的时候，就不需要再写.catch单独处理错误了
    instance.get('/data.json').then(res => {
        console.log(res)
    })
    // 如果觉得在拦截器中的错误处理还不够，需要单独为这个接口添加错误处理时，也可以在.then()后面再加上.catch()
    // 从而实现为这个接口单独添加更多的错误处理

```